require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LifestylesController do

  # This should return the minimal set of attributes required to create a valid
  # Lifestyle. As you add validations to Lifestyle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lifestyles as @lifestyles" do
      lifestyle = Lifestyle.create! valid_attributes
      get :index
      assigns(:lifestyles).should eq([lifestyle])
    end
  end

  describe "GET show" do
    it "assigns the requested lifestyle as @lifestyle" do
      lifestyle = Lifestyle.create! valid_attributes
      get :show, :id => lifestyle.id.to_s
      assigns(:lifestyle).should eq(lifestyle)
    end
  end

  describe "GET new" do
    it "assigns a new lifestyle as @lifestyle" do
      get :new
      assigns(:lifestyle).should be_a_new(Lifestyle)
    end
  end

  describe "GET edit" do
    it "assigns the requested lifestyle as @lifestyle" do
      lifestyle = Lifestyle.create! valid_attributes
      get :edit, :id => lifestyle.id.to_s
      assigns(:lifestyle).should eq(lifestyle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lifestyle" do
        expect {
          post :create, :lifestyle => valid_attributes
        }.to change(Lifestyle, :count).by(1)
      end

      it "assigns a newly created lifestyle as @lifestyle" do
        post :create, :lifestyle => valid_attributes
        assigns(:lifestyle).should be_a(Lifestyle)
        assigns(:lifestyle).should be_persisted
      end

      it "redirects to the created lifestyle" do
        post :create, :lifestyle => valid_attributes
        response.should redirect_to(Lifestyle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lifestyle as @lifestyle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lifestyle.any_instance.stub(:save).and_return(false)
        post :create, :lifestyle => {}
        assigns(:lifestyle).should be_a_new(Lifestyle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lifestyle.any_instance.stub(:save).and_return(false)
        post :create, :lifestyle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lifestyle" do
        lifestyle = Lifestyle.create! valid_attributes
        # Assuming there are no other lifestyles in the database, this
        # specifies that the Lifestyle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lifestyle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => lifestyle.id, :lifestyle => {'these' => 'params'}
      end

      it "assigns the requested lifestyle as @lifestyle" do
        lifestyle = Lifestyle.create! valid_attributes
        put :update, :id => lifestyle.id, :lifestyle => valid_attributes
        assigns(:lifestyle).should eq(lifestyle)
      end

      it "redirects to the lifestyle" do
        lifestyle = Lifestyle.create! valid_attributes
        put :update, :id => lifestyle.id, :lifestyle => valid_attributes
        response.should redirect_to(lifestyle)
      end
    end

    describe "with invalid params" do
      it "assigns the lifestyle as @lifestyle" do
        lifestyle = Lifestyle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lifestyle.any_instance.stub(:save).and_return(false)
        put :update, :id => lifestyle.id.to_s, :lifestyle => {}
        assigns(:lifestyle).should eq(lifestyle)
      end

      it "re-renders the 'edit' template" do
        lifestyle = Lifestyle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lifestyle.any_instance.stub(:save).and_return(false)
        put :update, :id => lifestyle.id.to_s, :lifestyle => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lifestyle" do
      lifestyle = Lifestyle.create! valid_attributes
      expect {
        delete :destroy, :id => lifestyle.id.to_s
      }.to change(Lifestyle, :count).by(-1)
    end

    it "redirects to the lifestyles list" do
      lifestyle = Lifestyle.create! valid_attributes
      delete :destroy, :id => lifestyle.id.to_s
      response.should redirect_to(lifestyles_url)
    end
  end

end
