require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LifestyelsController do

  # This should return the minimal set of attributes required to create a valid
  # Lifestyel. As you add validations to Lifestyel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lifestyels as @lifestyels" do
      lifestyel = Lifestyel.create! valid_attributes
      get :index
      assigns(:lifestyels).should eq([lifestyel])
    end
  end

  describe "GET show" do
    it "assigns the requested lifestyel as @lifestyel" do
      lifestyel = Lifestyel.create! valid_attributes
      get :show, :id => lifestyel.id.to_s
      assigns(:lifestyel).should eq(lifestyel)
    end
  end

  describe "GET new" do
    it "assigns a new lifestyel as @lifestyel" do
      get :new
      assigns(:lifestyel).should be_a_new(Lifestyel)
    end
  end

  describe "GET edit" do
    it "assigns the requested lifestyel as @lifestyel" do
      lifestyel = Lifestyel.create! valid_attributes
      get :edit, :id => lifestyel.id.to_s
      assigns(:lifestyel).should eq(lifestyel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lifestyel" do
        expect {
          post :create, :lifestyel => valid_attributes
        }.to change(Lifestyel, :count).by(1)
      end

      it "assigns a newly created lifestyel as @lifestyel" do
        post :create, :lifestyel => valid_attributes
        assigns(:lifestyel).should be_a(Lifestyel)
        assigns(:lifestyel).should be_persisted
      end

      it "redirects to the created lifestyel" do
        post :create, :lifestyel => valid_attributes
        response.should redirect_to(Lifestyel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lifestyel as @lifestyel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lifestyel.any_instance.stub(:save).and_return(false)
        post :create, :lifestyel => {}
        assigns(:lifestyel).should be_a_new(Lifestyel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lifestyel.any_instance.stub(:save).and_return(false)
        post :create, :lifestyel => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lifestyel" do
        lifestyel = Lifestyel.create! valid_attributes
        # Assuming there are no other lifestyels in the database, this
        # specifies that the Lifestyel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lifestyel.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => lifestyel.id, :lifestyel => {'these' => 'params'}
      end

      it "assigns the requested lifestyel as @lifestyel" do
        lifestyel = Lifestyel.create! valid_attributes
        put :update, :id => lifestyel.id, :lifestyel => valid_attributes
        assigns(:lifestyel).should eq(lifestyel)
      end

      it "redirects to the lifestyel" do
        lifestyel = Lifestyel.create! valid_attributes
        put :update, :id => lifestyel.id, :lifestyel => valid_attributes
        response.should redirect_to(lifestyel)
      end
    end

    describe "with invalid params" do
      it "assigns the lifestyel as @lifestyel" do
        lifestyel = Lifestyel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lifestyel.any_instance.stub(:save).and_return(false)
        put :update, :id => lifestyel.id.to_s, :lifestyel => {}
        assigns(:lifestyel).should eq(lifestyel)
      end

      it "re-renders the 'edit' template" do
        lifestyel = Lifestyel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lifestyel.any_instance.stub(:save).and_return(false)
        put :update, :id => lifestyel.id.to_s, :lifestyel => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lifestyel" do
      lifestyel = Lifestyel.create! valid_attributes
      expect {
        delete :destroy, :id => lifestyel.id.to_s
      }.to change(Lifestyel, :count).by(-1)
    end

    it "redirects to the lifestyels list" do
      lifestyel = Lifestyel.create! valid_attributes
      delete :destroy, :id => lifestyel.id.to_s
      response.should redirect_to(lifestyels_url)
    end
  end

end
