require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MallmanagersController do

  # This should return the minimal set of attributes required to create a valid
  # Mallmanager. As you add validations to Mallmanager, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all mallmanagers as @mallmanagers" do
      mallmanager = Mallmanager.create! valid_attributes
      get :index
      assigns(:mallmanagers).should eq([mallmanager])
    end
  end

  describe "GET show" do
    it "assigns the requested mallmanager as @mallmanager" do
      mallmanager = Mallmanager.create! valid_attributes
      get :show, :id => mallmanager.id.to_s
      assigns(:mallmanager).should eq(mallmanager)
    end
  end

  describe "GET new" do
    it "assigns a new mallmanager as @mallmanager" do
      get :new
      assigns(:mallmanager).should be_a_new(Mallmanager)
    end
  end

  describe "GET edit" do
    it "assigns the requested mallmanager as @mallmanager" do
      mallmanager = Mallmanager.create! valid_attributes
      get :edit, :id => mallmanager.id.to_s
      assigns(:mallmanager).should eq(mallmanager)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mallmanager" do
        expect {
          post :create, :mallmanager => valid_attributes
        }.to change(Mallmanager, :count).by(1)
      end

      it "assigns a newly created mallmanager as @mallmanager" do
        post :create, :mallmanager => valid_attributes
        assigns(:mallmanager).should be_a(Mallmanager)
        assigns(:mallmanager).should be_persisted
      end

      it "redirects to the created mallmanager" do
        post :create, :mallmanager => valid_attributes
        response.should redirect_to(Mallmanager.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mallmanager as @mallmanager" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mallmanager.any_instance.stub(:save).and_return(false)
        post :create, :mallmanager => {}
        assigns(:mallmanager).should be_a_new(Mallmanager)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mallmanager.any_instance.stub(:save).and_return(false)
        post :create, :mallmanager => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mallmanager" do
        mallmanager = Mallmanager.create! valid_attributes
        # Assuming there are no other mallmanagers in the database, this
        # specifies that the Mallmanager created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mallmanager.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => mallmanager.id, :mallmanager => {'these' => 'params'}
      end

      it "assigns the requested mallmanager as @mallmanager" do
        mallmanager = Mallmanager.create! valid_attributes
        put :update, :id => mallmanager.id, :mallmanager => valid_attributes
        assigns(:mallmanager).should eq(mallmanager)
      end

      it "redirects to the mallmanager" do
        mallmanager = Mallmanager.create! valid_attributes
        put :update, :id => mallmanager.id, :mallmanager => valid_attributes
        response.should redirect_to(mallmanager)
      end
    end

    describe "with invalid params" do
      it "assigns the mallmanager as @mallmanager" do
        mallmanager = Mallmanager.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mallmanager.any_instance.stub(:save).and_return(false)
        put :update, :id => mallmanager.id.to_s, :mallmanager => {}
        assigns(:mallmanager).should eq(mallmanager)
      end

      it "re-renders the 'edit' template" do
        mallmanager = Mallmanager.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mallmanager.any_instance.stub(:save).and_return(false)
        put :update, :id => mallmanager.id.to_s, :mallmanager => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mallmanager" do
      mallmanager = Mallmanager.create! valid_attributes
      expect {
        delete :destroy, :id => mallmanager.id.to_s
      }.to change(Mallmanager, :count).by(-1)
    end

    it "redirects to the mallmanagers list" do
      mallmanager = Mallmanager.create! valid_attributes
      delete :destroy, :id => mallmanager.id.to_s
      response.should redirect_to(mallmanagers_url)
    end
  end

end
