require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RetaileradminsController do

  # This should return the minimal set of attributes required to create a valid
  # Retaileradmin. As you add validations to Retaileradmin, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all retaileradmins as @retaileradmins" do
      retaileradmin = Retaileradmin.create! valid_attributes
      get :index
      assigns(:retaileradmins).should eq([retaileradmin])
    end
  end

  describe "GET show" do
    it "assigns the requested retaileradmin as @retaileradmin" do
      retaileradmin = Retaileradmin.create! valid_attributes
      get :show, :id => retaileradmin.id.to_s
      assigns(:retaileradmin).should eq(retaileradmin)
    end
  end

  describe "GET new" do
    it "assigns a new retaileradmin as @retaileradmin" do
      get :new
      assigns(:retaileradmin).should be_a_new(Retaileradmin)
    end
  end

  describe "GET edit" do
    it "assigns the requested retaileradmin as @retaileradmin" do
      retaileradmin = Retaileradmin.create! valid_attributes
      get :edit, :id => retaileradmin.id.to_s
      assigns(:retaileradmin).should eq(retaileradmin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Retaileradmin" do
        expect {
          post :create, :retaileradmin => valid_attributes
        }.to change(Retaileradmin, :count).by(1)
      end

      it "assigns a newly created retaileradmin as @retaileradmin" do
        post :create, :retaileradmin => valid_attributes
        assigns(:retaileradmin).should be_a(Retaileradmin)
        assigns(:retaileradmin).should be_persisted
      end

      it "redirects to the created retaileradmin" do
        post :create, :retaileradmin => valid_attributes
        response.should redirect_to(Retaileradmin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved retaileradmin as @retaileradmin" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retaileradmin.any_instance.stub(:save).and_return(false)
        post :create, :retaileradmin => {}
        assigns(:retaileradmin).should be_a_new(Retaileradmin)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retaileradmin.any_instance.stub(:save).and_return(false)
        post :create, :retaileradmin => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested retaileradmin" do
        retaileradmin = Retaileradmin.create! valid_attributes
        # Assuming there are no other retaileradmins in the database, this
        # specifies that the Retaileradmin created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Retaileradmin.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => retaileradmin.id, :retaileradmin => {'these' => 'params'}
      end

      it "assigns the requested retaileradmin as @retaileradmin" do
        retaileradmin = Retaileradmin.create! valid_attributes
        put :update, :id => retaileradmin.id, :retaileradmin => valid_attributes
        assigns(:retaileradmin).should eq(retaileradmin)
      end

      it "redirects to the retaileradmin" do
        retaileradmin = Retaileradmin.create! valid_attributes
        put :update, :id => retaileradmin.id, :retaileradmin => valid_attributes
        response.should redirect_to(retaileradmin)
      end
    end

    describe "with invalid params" do
      it "assigns the retaileradmin as @retaileradmin" do
        retaileradmin = Retaileradmin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retaileradmin.any_instance.stub(:save).and_return(false)
        put :update, :id => retaileradmin.id.to_s, :retaileradmin => {}
        assigns(:retaileradmin).should eq(retaileradmin)
      end

      it "re-renders the 'edit' template" do
        retaileradmin = Retaileradmin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retaileradmin.any_instance.stub(:save).and_return(false)
        put :update, :id => retaileradmin.id.to_s, :retaileradmin => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested retaileradmin" do
      retaileradmin = Retaileradmin.create! valid_attributes
      expect {
        delete :destroy, :id => retaileradmin.id.to_s
      }.to change(Retaileradmin, :count).by(-1)
    end

    it "redirects to the retaileradmins list" do
      retaileradmin = Retaileradmin.create! valid_attributes
      delete :destroy, :id => retaileradmin.id.to_s
      response.should redirect_to(retaileradmins_url)
    end
  end

end
